version: "3.3"

services:
  web:
    image: nodeweb
    restart: always
    build: 
      context: ./web
    volumes: 
      - ./web:/app
    command: yarn dev
    ports: 
      - 8080:8080
    networks:
      - erudion
    environment:
      PORT: 8080

networks: 
  erudion: